# Dockerfile
# Dockerfile

FROM java:latest

WORKDIR /app/java_project/

# Copy the jar
# COPY target/dockerized-0.0.1-SNAPSHOT.jar ./

# Copy dependencies

# Run the jar (CMD)
CMD ["java","-jar", "dockerized-0.0.1-SNAPSHOT.jar"]